/*
 * Stoatworks Labs - About window data for Cogwheel.
 *
 * HAND-WRITTEN PLACEHOLDER. Every other repo in the fleet has this file
 * GENERATED by stoatworks-backend/scripts/sync-about.py from the website's
 * projects.json, which is where those facts are actually written down.
 * Cogwheel has no entry there yet, so sync-about.py cannot generate it and the
 * URLs below point at pages that do not exist.
 *
 * What that means in practice: the four About buttons in the plugin's inspector
 * open 404s. Fix by adding cogwheel to projects.json and running the sync, at
 * which point this file is overwritten and stops being a placeholder. Until
 * then, do not "correct" the URLs here -- the sync is the fix.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Cogwheel";
    inline constexpr auto slug = "cogwheel";
    inline constexpr auto hook = "Spirograph machine for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "https://stoatworks-labs.com/software/cogwheel/guide/";
    inline constexpr auto page = "https://stoatworks-labs.com/software/cogwheel/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/cogwheel";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
